name: push-workflow

on:
  push:
    branches:
      - "*"
      - "!gh-readonly-queue/*"
  merge_group:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure btrfs
        run: sudo apt install btrfs-progs -y
      - name: List blks
        run: lsblk -e7
      - name: what is there now
        run: df --print-type
      - name: ls
        run: ls -a /mnt
      - name: swapoff
        run: sudo swapoff /mnt/swapfile
      - name: clear
        run: sudo rm -rf /mnt/*
      - name: unmount
        run: sudo bash -c 'umount /mnt && mkfs.btrfs -f -L fastspace /dev/sdb1'
      - name: make dir
        run: sudo mkdir -v /fastspace
      - name: mount
        run: sudo mount /dev/sdb1 /fastspace
